# Generated by Django 3.2.25 on 2024-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0003_auto_20240527_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='employee with suppliers', max_length=255),
        ),
    ]
