# Generated by Django 3.2.25 on 2024-05-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0010_promocode_usedpromocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='valid_to',
        ),
    ]
