# Generated by Django 3.2.25 on 2024-05-31 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busyness', '0012_promocode_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customers_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='employees_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busyness.promocode'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busyness.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busyness.sale')),
            ],
        ),
    ]
