# Generated by Django 3.2.25 on 2024-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0015_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('logo', models.ImageField(default='images/no.jpeg', upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Company Video')),
                ('history_by_years', models.TextField(blank=True, verbose_name='History by Years')),
                ('requisites', models.TextField(blank=True, verbose_name='Company Requisites')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Company Certificate')),
            ],
        ),
    ]
