# Generated by Django 3.2.25 on 2024-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0019_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Company Certificate'),
        ),
    ]
