# Generated by Django 3.2.25 on 2024-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0021_alter_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=25500),
        ),
    ]
