# Generated by Django 3.2.25 on 2024-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0022_alter_vacancy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default='images/no.jpeg', upload_to='images/'),
        ),
    ]
