# Generated by Django 3.2.25 on 2024-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0023_vacancy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=False)),
                ('delay', models.PositiveIntegerField(default=5)),
                ('loop', models.BooleanField(default=False)),
                ('navs', models.BooleanField(default=True)),
                ('pags', models.BooleanField(default=True)),
                ('stopMouseHover', models.BooleanField(default=False)),
            ],
        ),
    ]
