# Generated by Django 3.2.25 on 2024-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0024_slidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='maks.kree@mail.ru', max_length=254),
        ),
    ]
